### PR TITLE
Correctly place the font drawing box at the center between baseline and capline

### PR DESCRIPTION
**Pull request by EsoFromTheEast**

### CODE REVIEW

**Comment by rsheeter** [comment]
As described (center the path) this sounds like it's overriding how the icon designer positioned things. For example, an icon that's just a bar right on the capline would end up moving down. Is the description possibly wrong?

**Comment by EsoFromTheEast** [comment]
> As described (center the path) this sounds like it's overriding how the icon designer positioned things. For example, an icon that's just a bar right on the capline would end up moving down. Is the description possibly wrong?
I updated the description, the center of the SVG will be at the center of baseline/capline, so if an icon is at the top, it will touch the capline

**Comment by rsheeter** [comment]
Still doesn't seem right. Are you positioning the *path* - sounds unlikely to be correct; moving the path vertically in font space would become ignored - or the entire box the font is drawing into?

**Comment by EsoFromTheEast** [comment]
the entire box is being shifted so the icon is not losing the original alignment

**Review by rsheeter — APPROVED** [review]

**Comment by rsheeter** [comment]
OK cool, that sounds safer. Ty for clarifying.

**Pull request merged**
